apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend2
  template:
    metadata:
      labels:
        tier: backend2
    spec:
      containers:
        - name: main
          image: nginx:latest