apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend2
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend2
  template:
    metadata:
      labels:
        tier: frontend2
    spec:
      containers:
        - name: main
          image: nginx:latest